name: Import TPS format - MAIN
on:
  push:
    branches:
      - "main"
    paths:
      - tasks/**
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TPS
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix zip
          sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/ioi-2017/tps/master/online-installer/install.sh)"

      - name: Generate and export tasks
        run: |
          set +e
          ls -lha
          mkdir -p cms
          for dir in $(find tasks -maxdepth 1 -type d -not -path '*/\.*' -not -path './cms' -not -path '..commons' -not -path '.'); do
          if [ -d "$dir" ] && [ "$(basename "$dir")" != "tasks" ]; then
              echo "Processing directory: $dir ................."
              rm "tasks/$(basename "$dir")"/*.zip
              ./scripts/task-prepare-folder.sh "$(basename "$dir")"
              ./scripts/task-gen-cases.sh "$(basename "$dir")"
              ./scripts/task-gen-zip.sh "$(basename "$dir")"
              cp "tasks/$(basename "$dir")"/*.zip cms
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cms-artifact
          path: cms

  importTasks:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cms-artifact
          path: cms

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create folder
        run: ls -lha

      - name: Create folder
        run: ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} "rm -rf dataset && mkdir dataset || mkdir dataset"

      - name: Upload all tasks to server
        run: |
          ls -lha
          scp -r cms ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }}:dataset/

      - name: Import Tasks in available formats
        run: |
              ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} 'bash -s' <<'ENDSSH'
              set +e

               #List all statements in zip format
               cd dataset/cms
               for dir in $(find -name '*.zip'); do
                 unzip $dir;
               done

               for dir in $(find -maxdepth 1 -type d -not -path '.'); do
                   if [ -d "$dir" ]; then
                     /opt/.venv/bin/cmsImportTask -L tps_task "$(basename "$dir")" --update

                 		for lang_file in $(find "$dir/statements/" -maxdepth 1 -type f); do
                 			lang_code=$(basename "$lang_file" .pdf)
                     	/opt/.venv/bin/cmsAddStatement "$(basename "$dir")" $lang_code "$(basename "$dir")"/statement/statement.pdf
               	  	done
                   fi
               done
              ENDSSH
