name: Import Italy format - MAIN
on:
  push:
    branches:
      - "main"
    paths:
      - tasks-italy/**
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cms-artifact
          path: cms
          
  importTasks:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cms-artifact
          path: cms

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create folder
        run: ls -lha

      - name: Create folder
        run: ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} "rm -rf dataset && mkdir dataset || mkdir dataset"

      - name: Upload all tasks to server
        run: |
          ls -lha
          scp -r cms ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }}:dataset/
  
      - name: Import Tasks
        run: |
          ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} 'bash -s' <<'ENDSSH'
          cd cms 
          set +e
          ls -lha
          cd tasks-italy
          cmsImportContest -i -L italy_yaml . --update-contest --update-tasks
          ENDSSH

